export const ALL_CARTS_PRODUCTS = 'ALL_CARTS_PRODUCTS';
export const EDIT_CART = 'EDIT_CART';
export const CHOOSE_CART = 'CHOOSE_CART';
export const CHOOSE_ALL = 'CHOOSE_ALL';
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT';
export const DEL_CART_PRODUCT = 'DEL_CART_PRODUCT';
export const GET_CART_INFO = 'GET_CART_INFO';
export const ASSIGN_SETTLE_CHOOSEIDS = 'ASSIGN_SETTLE_CHOOSEIDS';